source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in pdf_generator.gemspec
gemspec
gem "sinatra"
gem "prawn"
gem "shotgun"
gem "bunny"