source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in top_contributors.gemspec
gemspec

gem "sinatra"
gem "slim"
gem "shotgun"
gem "bunny"